source 'https://github.com/CocoaPods/Specs.git'

target 'EmailFeedback', :exclusive => true do
  pod "EmailFeedback", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "EmailFeedback", :path => "../"

  
end
